#!/bin/sh

set -e

GAME_EXEC=
GAME_SAVE=
GAME_PASS='Server2011$'
GAME_MOTD='Welcome to the server!'
GAME_NAME=terraria
GAME_PORT=7777

server_exec_unix() {
  if ! pkg screen; then
    die "screen not installed"
  fi

  exec screen -Dm -S "$GAME_NAME" \
    "$GAME_EXEC" \
    -world "$GAME_SAVE" \
    -password "$GAME_PASS" \
    -motd "$GAME_MOTD" \
    -players 255 \
    -port "$GAME_PORT" \
    -noupnp
}

server_exec_mono() {
  if ! pkg screen; then
    die "screen not installed"
  fi

  if ! pkg mono; then
    die "mono not installed"
  fi

  exec screen -Dm -S "$GAME_NAME" \
    mono --server --gc=sgen -O=all \
    "$GAME_EXEC" \
    -world "$GAME_SAVE" \
    -password "$GAME_PASS" \
    -motd "$GAME_MOTD" \
    -players 255 \
    -port "$GAME_PORT" \
    -noupnp
}

server_exec() {
  if [ ! -f "$GAME_EXEC" ]; then
    die "executable not found"
  fi

  if [ ! -f "$GAME_SAVE" ]; then
    die "world not found"
  fi

  if [ -z "$GAME_PASS" ]; then
    die "password not found"
  fi

  if [ -z "$GAME_MOTD" ]; then
    die "message not found"
  fi

  if [ -z "$GAME_NAME" ]; then
    die "screen not found"
  fi

  if [ -z "$GAME_PORT" ]; then
    die "port not found"
  fi

  GAME_EXEC_NAME="${GAME_EXEC##*/}"
  case $GAME_EXEC_NAME in
    TerrariaServer | TerrariaServer.bin.x86_64)
      server_exec_unix
      ;;
    TerrariaServer.exe)
      server_exec_mono
      ;;
    *)
      die "unknown executable"
      ;;
  esac
}

server_tty() {
  if ! screen -S "$GAME_NAME" -r; then
    die "server not found"
  fi
}

server_cmd() {
  if ! screen -S "$GAME_NAME" -X stuff "${*}\n"; then
    die "server not found"
  fi
}

pkg() {
  command -v "$1" > /dev/null
}

die() {
  printf "%s: %s\n" "${0##*/}" "$*" >&2
  exit 1
}

while getopts :x:s:p:m:S:P opt; do
  case $opt in
    x)
      GAME_EXEC="$OPTARG"
      ;;
    s)
      GAME_SAVE="$OPTARG"
      ;;
    p)
      GAME_PASS="$OPTARG"
      ;;
    m)
      GAME_MOTD="$OPTARG"
      ;;
    S)
      GAME_NAME="$OPTARG"
      ;;
    P)
      GAME_PORT="$OPTARG"
      ;;
    *)
      die "unknown option"
      ;;
  esac
done
shift $((OPTIND - 1))

case $1 in
  x)
    server_exec
    ;;
  c)
    server_tty
    ;;
  s)
    server_cmd save
    ;;
  e)
    server_cmd exit
    ;;
  *)
    die "unknown option"
    ;;
esac
